[[problemas]]
vertices=2
quadrado=[[0,1]]

[[problemas]]
vertices=2
quadrado=[[0,1]]
circulo=[[0,1],[1,0]]

[[problemas]]
vertices=3
quadrado=[[0,1],[1,2],[2,0]]
circulo=[[0,2],[1,0]]

[[problemas]]
vertices=3
quadrado=[[0,2],[1,2],[2,0]]
circulo=[[0,1],[1,2],[2,0]]

[[problemas]]
vertices=3
quadrado=[[0,1],[1,0]]
circulo=[[0,1]]
triangulo=[[1,2],[2,1]]

[[problemas]]
vertices=3
quadrado=[[0,1],[1,0],[2,1]]
circulo=[[0,1],[1,2],[2,0]]

[[problemas]]
vertices=3
quadrado=[[0,1]]
circulo=[[0,1],[1,2],[2,0]]

[[problemas]]
vertices=3
quadrado=[[0,1],[1,2],[2,1]]
circulo=[[1,2],[2,1]]
triangulo=[[0,2],[2,0]]

[[problemas]]
vertices=4
quadrado=[[0,3],[2,3],[3,2]]
circulo=[[1,0],[3,1]]
triangulo=[[0,2],[2,3],[3,0]]

[[problemas]]
vertices=4
quadrado=[[0,1],[1,2],[2,0]]
circulo=[[3,2]]
triangulo=[[0,1]]

[[problemas]]
vertices=4
quadrado=[[0,1],[1,3],[2,0],[3,2]]
circulo=[[0,1],[1,0],[3,2]]

[[problemas]]
vertices=4
quadrado=[[0,3],[2,3],[3,2]]
circulo=[[0,2],[1,0],[2,1]]

[[problemas]]
vertices=4
quadrado=[[0,1]]
circulo=[[0,1],[1,3],[2,0],[3,2]]

[[problemas]]
vertices=4
quadrado=[[0,1],[1,2],[2,0]]
circulo=[[0,2],[1,3],[2,3],[3,1]]

[[problemas]]
vertices=4
quadrado=[[0,3],[1,3],[3,1]]
circulo=[[0,1],[1,0]]
triangulo=[[1,2],[2,1]]

[[problemas]]
vertices=5
quadrado=[[0,3],[1,0]]
circulo=[[0,3],[3,4],[4,3]]
triangulo=[[4,2]]

[[problemas]]
vertices=5
quadrado=[[1,3],[3,4],[4,1]]
circulo=[[1,3],[3,1]]
triangulo=[[0,1],[1,2]]

[[problemas]]
vertices=5
quadrado=[[0,2]]
circulo=[[0,2],[1,0],[2,4],[3,1],[4,3]]

[[problemas]]
vertices=5
quadrado=[[0,3],[1,2],[2,4],[3,1],[4,3]]
circulo=[[0,1],[1,0]]
triangulo=[[1,2],[2,1],[3,4],[4,3]]

[[problemas]]
vertices=5
quadrado=[[0,3],[2,0],[3,0]]
circulo=[[2,3],[3,2]]
triangulo=[[0,1],[1,0],[3,4],[4,3]]

[[problemas]]
vertices=5
quadrado=[[3,0]]
circulo=[[0,2],[2,3],[3,2]]
triangulo=[[1,2],[2,1],[3,4],[4,3]]
