name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup rust
        run: rustup update 1.88 && rustup default 1.88

      - name: Build
        run: |
          mkdir dist
          cargo build --package=syncro-solver --bin=syncro-solver --release
          cp target/release/syncro-solver dist/syncro-solver
          strip dist/syncro-solver

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist
          if-no-files-found: error

  macos:
    name: macOS Build
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup rust
        run: rustup update 1.88 && rustup default 1.88

      - name: Build
        run: |
          mkdir dist
          cargo build --package=syncro-solver --bin=syncro-solver --release
          cp target/release/syncro-solver dist/syncro-solver
          strip dist/syncro-solver

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist
          if-no-files-found: error

  windows:
    name: Windows Build
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup rust
        run: rustup update 1.88 && rustup default 1.88

      - name: Build
        run: |
          md dist
          cargo build --package=syncro-solver --bin=syncro-solver --release
          copy target/release/syncro-solver.exe dist/syncro-solver.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist
          if-no-files-found: error
